### ISSUE TITLE
Build error: an expression was expected of type

### ISSUE THREAD

**Issue by ghost** [winter2020/oo7#3]
Hello !

I've got some issues trying to compile ddtbd:

`+ ocamlfind ocamlc -c -g -short-paths -thread -package bap-primus -package bap-taint -package ppx_jane -package core_kernel -package bap -pp 'ppx-jane -dump-ast -inline-test-drop' -predicates custom_ppx -predicates ppxlib -o ddtbd.cmo ddtbd.ml`

`File "ddtbd.ml", line 316, characters 24-68:`
`Error: This expression has type`
         `(point, point tree, Word.comparator_witness) Map.t`
         `Map_intf.Or_duplicate.t`
      ` but an expression was expected of type`
        ` point tree Addr.Map.t =`
          ` (point, point tree, Word.comparator_witness) Map.t`
`Command exited with code 2.`
`Compilation unsuccessful after building 2 targets (1 cached) in 00:00:01.`

Any help would be great ! :)

**Comment by ivg** [comment]
Looks like that you're not using the bap 1.5 version. BAP has moved far away since this plugin was written and we need to move this ddtbd plugin under our umbrella, but so far, here are the instructions that will ensure that you have the right set of dependencies.

1. First of all, undo all that you have done :) Just delete the `.opam` folder if it works for you:
```
rm -rf ~/.opam
```
2. Next, make sure that you're using `opam 2.x` otherwise follow [the instructions][1] and install the latest version of opam.

3. Install the compiler and bap, don't forget to specify the version, do not pin or clone anything, i.e.,
```
opam init --compiler=4.05.0
eval $(opam env)
opam install bap.1.5.0 
```

(if you need system dependencies, you can also do `opam depext --install bap.1.5.0` instead of the last command).

Feel free also to drop by the BAP gitter channel if you have any problems. Meantime we will update this plugin to the latest version of BAP, so that you can just do `opam install bap-ddtbd` instead of all these complex instructions. 

------
You're using 1.5 while we are already working on 2.1

[1]: https://opam.ocaml.org/doc/Install.html
[2]: https://gitter.im/BinaryAnalysisPlatform/bap

**Comment by ghost** [comment]
Thanks it worked !!  :)

Here's what I did in case anyone has the same issue:
```bash
rm -rf ~/.opam
sudo pacman -S opam llvm7 # conf-bap-llvm.1.3 is not compatible with the latest version of llvm
opam switch create ocaml-base-compiler 4.03.0
opam install bap.1.5.0
```
